In [1]:
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("jhan21/amazon-beauty-reviews-dataset")

c:\Users\Muhamad Asqar\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
ds

DatasetDict({
    train: Dataset({
        features: ['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase'],
        num_rows: 701528
    })
})

In [3]:
# download vader_lexicon using nltk.download()
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import pandas as pd
import numpy as np

In [4]:
#fileName = "esteebrandsdata.csv"
column = "text"
Data = ds['train'].to_pandas()
Data = Data.replace(np.nan,' ',regex=True)
sentences = list(Data[column])

In [5]:
sid = SentimentIntensityAnalyzer()
sentiments = []
for sentence in sentences:
    ss = sid.polarity_scores(sentence)
    sentiments.append(ss)
sentiments_df = pd.DataFrame(sentiments)

In [6]:
sentiments_df

          neg    neu    pos  compound
0       0.062  0.745  0.193    0.8162
1       0.000  0.842  0.158    0.7430
2       0.000  0.215  0.785    0.8070
3       0.000  1.000  0.000    0.0000
4       0.000  0.192  0.808    0.6369
...       ...    ...    ...       ...
701523  0.000  0.594  0.406    0.6249
701524  0.164  0.635  0.200    0.1739
701525  0.000  1.000  0.000    0.0000
701526  0.070  0.562  0.367    0.9285
701527  0.048  0.767  0.185    0.6845

[701528 rows x 4 columns]

In [7]:
sentiments_df.insert(0, "text", Data[column].values)

In [8]:
def get_sentiment(compound):
    if compound >= 0.05:
        return "Positive"
    elif compound <= -0.05:
        return "Negative"
    else:
        return "Neutral"

sentiments_df["sentiment"] = sentiments_df["compound"].apply(get_sentiment)

sentiments_df.head()

,text,neg,neu,pos,compound,sentiment
0,This spray is really nice. It smells really go...,0.062,0.745,0.193,0.8162,Positive
1,"This product does what I need it to do, I just...",0.000,0.842,0.158,0.7430,Positive
2,"Smells good, feels great!",0.000,0.215,0.785,0.8070,Positive
3,Felt synthetic,0.000,1.000,0.000,0.0000,Neutral
4,Love it,0.000,0.192,0.808,0.6369,Positive

In [9]:
sentiments_df.to_csv("sentiments.csv", index=False)